import Foundation

enum TraceLocalization {
    static var current: AppLanguage = .english

    static func text(_ key: String) -> String {
        guard current != .simplifiedChinese else { return key }
        if let translated = tables[current]?[key] {
            return translated
        }
        return tables[.english]?[key] ?? key
    }

    static var locale: Locale {
        Locale(identifier: current.localeIdentifier)
    }

    static var languageInstruction: String {
        current.promptInstruction
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "计划": "Plan",
            "目标": "Goal",
            "待开始": "Planned",
            "进行中": "In Progress",
            "已完成": "Done",
            "低": "Low",
            "中": "Medium",
            "高": "High",
            "日间": "Day",
            "暗夜": "Night",
            "自定义": "Custom",
            "明亮、清爽、低对比": "Bright, clean, low contrast",
            "深色、沉静、护眼": "Dark, calm, eye-friendly",
            "18bit 色深，自由调侧边栏玻璃色": "18-bit color, fully custom global tint",
            "今日": "Today",
            "规划": "Planning",
            "监控": "Monitor",
            "教练": "Coach",
            "设置": "Settings",
            "记录与教练": "Records & Coach",
            "工作台": "Workspace",
            "展开侧边栏": "Show Sidebar",
            "折叠侧边栏": "Hide Sidebar",
            "新对话": "New Chat",
            "收起对话": "Collapse Chats",
            "展开对话": "Expand Chats",
            "对话标题": "Chat Title",
            "确认": "Confirm",
            "取消": "Cancel",
            "重命名": "Rename",
            "删除对话": "Delete Chat",
            "删除对话？": "Delete chat?",
            "删除": "Delete",
            "删除后不会影响教练记忆和身份信息。": "Deleting this chat will not delete coach memory or identity information.",
            "正在记录": "Recording",
            "记录暂停": "Recording Paused",
            "等待采样": "Waiting for Sample",
            "今日计划": "Today Plans",
            "暂无今日计划": "No plans for today",
            "日记标题": "Diary Title",
            "完成细节与感想": "Completion details and reflections",
            "记录日记": "Save Diary",
            "记录并完成": "Save and Complete",
            "目标推进": "Goal Progress",
            "暂无长期目标": "No long-term goals",
            "阶段日志标题": "Stage Log Title",
            "阶段完成情况与感想": "Stage progress and reflections",
            "记录阶段日志": "Save Stage Log",
            "长期目标与短期计划": "Long-term goals and short-term plans",
            "学习": "Study",
            "新计划": "New Plan",
            "计划名称": "Plan Name",
            "完成信号或备注": "Completion signal or note",
            "项目": "Project",
            "开始日期": "Start Date",
            "完成日期": "Completion Date",
            "完成日期不能早于开始日期": "Completion date cannot be earlier than start date",
            "优先级": "Priority",
            "添加计划": "Add Plan",
            "新目标": "New Goal",
            "目标名称": "Goal Name",
            "为什么做": "Why It Matters",
            "衡量方式": "Measure",
            "周期": "Duration",
            "天": "days",
            "添加目标": "Add Goal",
            "规划概览": "Planning Overview",
            "日志": "Logs",
            "计划日历": "Plan Calendar",
            "暂无计划": "No plans",
            "开始": "Start",
            "完成": "Due",
            "目标日志": "Goal Logs",
            "暂无目标": "No goals",
            "暂无阶段日志": "No stage logs",
            "阶段日志": "Stage Logs",
            "全文": "Full Text",
            "截止": "Due",
            "记录时长、应用分布与窗口轨迹": "Recording time, app usage, and window timeline",
            "今日记录": "Today Record",
            "时长": "Duration",
            "样本": "Samples",
            "状态": "Status",
            "暂停": "Paused",
            "当前采样": "Current Sample",
            "应用": "App",
            "窗口": "Window",
            "未获取": "Not captured",
            "时间": "Time",
            "进程": "Process",
            "屏幕": "Screen",
            "暂无采样": "No samples",
            "立即采样": "Sample Now",
            "对话、记忆与规划动作": "Chat, memory, and planning actions",
            "当前对话": "Current Chat",
            "暂无对话": "No messages",
            "教练正在思考": "Coach is thinking",
            "发送": "Send",
            "今日复盘": "Today Review",
            "暂无复盘": "No review yet",
            "记忆": "Memory",
            "暂无长期记忆": "No long-term memory",
            "身份、接口、外观与采样": "Identity, API, appearance, and sampling",
            "身份信息": "Identity",
            "例如：大一计算机科学学生、高中数学偏科生": "For example: first-year computer science student, high-school student weak in math",
            "教练会把身份信息作为长期背景。修改已有身份会先归档当前身份下的记忆和全部对话，再开启新的身份记忆。": "The coach uses identity as long-term context. Changing an existing identity archives memory and all chats under the current identity, then starts a new identity memory.",
            "保存身份": "Save Identity",
            "修改身份": "Change Identity",
            "当前：": "Current: ",
            "外观": "Appearance",
            "主题": "Theme",
            "语言": "Language",
            "AI 接口": "AI API",
            "模型": "Model",
            "保存 Key": "Save Key",
            "采样": "Sampling",
            "频率": "Frequency",
            "秒": "sec",
            "分钟": "min",
            "分": "min",
            "记录窗口标题": "Record window titles",
            "保存屏幕快照": "Save screenshots",
            "快照间隔": "Screenshot interval",
            "修改身份信息？": "Change identity?",
            "确认归档并修改": "Archive and Change",
            "这会归档当前身份下的教练记忆和所有对话，然后为新身份开启新的记忆与对话。": "This will archive coach memory and all chats under the current identity, then start memory and chats for the new identity.",
            "已归档对话": "Archived Chats",
            "暂无归档": "No archives",
            "条消息": "messages",
            "自定义全局主题色": "Custom Global Theme Color",
            "应用时间": "App Time",
            "开始记录后显示": "Shown after recording starts",
            "窗口轨迹": "Window Timeline",
            "暂无轨迹": "No timeline",
            "未设置身份": "No Identity Set",
            "对话": "Conversation",
            "今日对话": "Today Chat",
            "新身份对话": "New Identity Chat",
            "身份信息从": "Identity changed from",
            "修改为": "to",
            "已切换到身份": "Switched to identity",
            "我会基于这个身份重新建立对话记忆。": "I will rebuild chat memory around this identity.",
            "每日自动归档": "Daily auto archive",
            "归档文件写入失败": "Archive file write failed",
            "API Key 已保存到钥匙串": "API Key saved to Keychain",
            "教练复盘已生成": "Coach review generated",
            "已生成本地复盘": "Generated local review",
            "教练使用本地降级": "Coach used local fallback",
            "归档对话": "Archived Chat",
            "默认对话": "Default Chat",
            "旧对话": "Old Chat",
            "未命名记录": "Untitled Note",
            "我": "Me",
            "工具": "Tool",
            "系统": "System",
            "完成可验证产出": "Complete a verifiable output",
            "明确下一步动作": "Clarify the next action",
            "完成一次阶段复盘": "Complete one stage review",
            "产出可展示成果": "Produce a demonstrable result",
            "未完成": "Not Done",
            "无计划": "No plans",
            "无目标": "No goals",
            "无今日任务": "No tasks today",
            "无长期目标": "No long-term goals",
            "暂无日志": "No logs",
            "暂无总结": "No summaries",
            "暂无窗口轨迹": "No window timeline",
            "暂无应用分布": "No app distribution",
            "本地启发式": "Local Heuristic",
            "空响应": "Empty response",
            "还没有保存 API Key": "No API Key has been saved",
            "API URL 无效": "Invalid API URL",
            "AI 服务返回异常": "AI service returned an error",
            "AI 没有返回可读内容。": "AI did not return readable content.",
            "AI JSON 编码无效": "AI JSON encoding is invalid",
            "教练 JSON 编码无效": "Coach JSON encoding is invalid",
            "我读完了当前规划上下文，但模型回复没有给出可展示内容。": "I read the current planning context, but the model did not provide a displayable reply.",
            "新增计划失败：缺少标题。": "Failed to add plan: missing title.",
            "更新计划失败：未找到目标计划。": "Failed to update plan: target plan not found.",
            "删除计划失败：未找到目标计划。": "Failed to delete plan: target plan not found.",
            "完成计划失败：未找到目标计划。": "Failed to complete plan: target plan not found.",
            "添加计划日记失败：未找到目标计划。": "Failed to add plan diary: target plan not found.",
            "新增目标失败：缺少标题。": "Failed to add goal: missing title.",
            "更新目标失败：未找到目标。": "Failed to update goal: target goal not found.",
            "删除目标失败：未找到目标。": "Failed to delete goal: target goal not found.",
            "更新目标进度失败：缺少目标或进度。": "Failed to update goal progress: missing goal or progress.",
            "添加目标日志失败：未找到目标。": "Failed to add goal log: target goal not found.",
            "已新增计划": "Added plan",
            "已更新计划": "Updated plan",
            "已删除计划": "Deleted plan",
            "已标记完成": "Marked complete",
            "已添加计划日记": "Added plan diary",
            "已新增目标": "Added goal",
            "已更新目标": "Updated goal",
            "已删除目标": "Deleted goal",
            "已更新目标进度": "Updated goal progress",
            "已添加目标日志": "Added goal log",
            "已读取上下文": "Read context",
            "最近日志": "Recent logs",
            "教练文件区暂无文件。": "Coach files area is empty.",
            "教练文件": "Coach files",
            "读取文件失败": "Failed to read file",
            "已读取": "Read",
            "写入文件失败：内容为空。": "Failed to write file: content is empty.",
            "已写入教练文件": "Wrote coach file",
            "写入文件失败": "Failed to write file",
            "AI 服务暂时不可用，我先用本地数据给出简要复盘": "AI service is temporarily unavailable, so I used local data for a brief review",
            "AI 服务暂时不可用，我可以先读取本地上下文": "AI service is temporarily unavailable. I can read the local context first",
            "服务原因": "Reason",
            "教练暂时无法调用模型": "Coach cannot call the model right now",
            "本地数据仍可查看，计划与目标可以在规划里继续编辑。": "Local data is still available, and plans and goals can still be edited in Planning.",
            "记录": "Recorded",
            "今日任务完成度较高。": "Today's task completion is strong.",
            "任务有推进，但闭环不足。": "Tasks moved forward, but closure is still weak.",
            "任务完成度偏低。": "Task completion is low.",
            "缺少今日任务，无法判断计划执行。": "There are no tasks today, so execution cannot be assessed.",
            "记录到较长学习/工作时段。": "A longer study/work block was recorded.",
            "记录到可用学习/工作时段。": "A usable study/work block was recorded.",
            "记录时长偏短。": "Recorded time is short.",
            "存在支撑长期目标的高优先级行动或日志。": "There is high-priority action or logging that supports long-term goals.",
            "有长期目标，但今日动作关联不强。": "There are long-term goals, but today's actions are weakly connected.",
            "短时段内应用切换偏多。": "There was frequent app switching in a short span.",
            "没有足够轨迹，基础分保守。": "There is not enough activity evidence, so the base score is conservative.",
            "有少量轨迹或任务信息，但不足以判断全天。": "There is some activity or task information, but not enough to assess the whole day.",
            "轨迹可覆盖一个以上学习片段。": "The activity trail covers more than one study segment.",
            "轨迹覆盖较长时间，证据质量较好。": "The trail covers a longer period with better evidence quality.",
            "无有效证据": "No useful evidence",
            "证据偏少": "Thin evidence",
            "证据可用": "Usable evidence",
            "证据充分": "Strong evidence",
            "很低": "Very Low",
            "置信度": "Confidence",
            "今天轨迹不足，结论只适合作为轻量提醒。": "Today's activity trail is thin, so conclusions should be treated as light reminders.",
            "AI 服务未完成": "AI service did not complete",
            "今天记录到": "Today recorded",
            "分钟轨迹，主要集中在": "minutes of activity, mainly in",
            "今天缺少连续轨迹，先把任务和目标补齐。": "Today lacks a continuous trail. Start by filling in tasks and goals.",
            "完成了": "Completed",
            "个今日任务": "tasks today",
            "已经开始建立记录入口。": "The recording workflow has been started.",
            "可先补一个长期目标。": "Add one long-term goal first.",
            "保留了": "Kept",
            "个长期目标": "long-term goals",
            "今天没有明确任务，评分只能保守。": "There were no clear tasks today, so the score must be conservative.",
            "计划闭环仍需加强。": "Plan closure still needs work.",
            "应用切换需要继续观察。": "App switching should continue to be watched.",
            "轨迹数据偏少，难以判断专注质量。": "The trail is too thin to judge focus quality.",
            "明早先写 1 个主线任务和完成信号。": "Tomorrow morning, write one main task and its completion signal first.",
            "每段学习结束后补 1 句产出记录。": "After each study block, add one sentence about the output.",
            "复盘时只保留 3 条最关键改进。": "During review, keep only the three most important improvements.",
            "选一个最高优先级任务先做 45 分钟。": "Pick the highest-priority task and work on it for 45 minutes first.",
            "完成后记录成果文件、页码或实验结果。": "After finishing, record the output file, page number, or experiment result.",
            "晚上用教练检查计划偏差。": "Use Coach tonight to check plan drift.",
            "总评": "Overview",
            "评分依据": "Score Basis",
            "亮点": "Highlights",
            "阻碍": "Obstacles",
            "改进建议": "Recommendations",
            "明日计划": "Tomorrow Plan",
            "数据边界": "Data Boundaries",
            "预计": "Estimate",
            "备注": "Note",
            "完成记录": "Completion Note",
            "日记": "Diary",
            "目的": "Purpose",
            "衡量": "Measure",
            "里程碑": "Milestones",
            "身份": "Identity",
            "摘要": "Summary",
            "关键事实": "Key Facts",
            "更新时间": "Updated",
            "无": "None",
            "记录时长": "Recorded Time",
            "应用分布": "App Distribution",
            "长期目标": "Long-term Goals",
            "进度": "Progress"
        ],
        .traditionalChinese: [
            "记录与教练": "記錄與教練", "工作台": "工作臺", "今日": "今日", "规划": "規劃", "监控": "監控", "教练": "教練", "设置": "設定",
            "计划": "計劃", "目标": "目標", "待开始": "待開始", "进行中": "進行中", "已完成": "已完成", "低": "低", "中": "中", "高": "高",
            "日间": "日間", "暗夜": "暗夜", "自定义": "自訂", "明亮、清爽、低对比": "明亮、清爽、低對比", "深色、沉静、护眼": "深色、沉靜、護眼", "18bit 色深，自由调侧边栏玻璃色": "18bit 色深，自由調整全域玻璃色",
            "今日计划": "今日計劃", "暂无今日计划": "暫無今日計劃", "目标推进": "目標推進", "暂无长期目标": "暫無長期目標",
            "长期目标与短期计划": "長期目標與短期計劃", "新计划": "新計劃", "计划名称": "計劃名稱", "完成信号或备注": "完成信號或備註", "项目": "項目", "开始日期": "開始日期", "完成日期": "完成日期", "添加计划": "新增計劃",
            "新目标": "新目標", "目标名称": "目標名稱", "为什么做": "為什麼做", "衡量方式": "衡量方式", "添加目标": "新增目標", "计划日历": "計劃日曆", "目标日志": "目標日誌",
            "对话、记忆与规划动作": "對話、記憶與規劃動作", "身份、接口、外观与采样": "身份、介面、外觀與採樣", "身份信息": "身份資訊", "外观": "外觀", "语言": "語言", "采样": "採樣",
            "已归档对话": "已歸檔對話", "暂无归档": "暫無歸檔", "应用时间": "應用時間", "窗口轨迹": "視窗軌跡", "未设置身份": "未設定身份",
            "教练正在思考": "教練正在思考", "发送": "傳送", "记忆": "記憶", "暂无长期记忆": "暫無長期記憶", "当前：": "目前："
        ],
        .japanese: [
            "计划": "計画", "目标": "目標", "今日": "今日", "规划": "プラン", "监控": "モニター", "教练": "コーチ", "设置": "設定",
            "记录与教练": "記録とコーチ", "工作台": "ワークスペース", "待开始": "未開始", "进行中": "進行中", "已完成": "完了", "低": "低", "中": "中", "高": "高",
            "日间": "ライト", "暗夜": "ダーク", "自定义": "カスタム", "今日计划": "今日の計画", "暂无今日计划": "今日の計画はありません", "目标推进": "目標の進捗", "暂无长期目标": "長期目標はありません",
            "长期目标与短期计划": "長期目標と短期計画", "新计划": "新しい計画", "计划名称": "計画名", "完成信号或备注": "完了条件またはメモ", "项目": "プロジェクト", "开始日期": "開始日", "完成日期": "完了日", "优先级": "優先度", "添加计划": "計画を追加",
            "新目标": "新しい目標", "目标名称": "目標名", "为什么做": "目的", "衡量方式": "測定方法", "添加目标": "目標を追加", "计划日历": "計画カレンダー", "目标日志": "目標ログ",
            "记录时长、应用分布与窗口轨迹": "記録時間、アプリ使用、ウィンドウ履歴", "对话、记忆与规划动作": "会話、記憶、プラン操作", "身份信息": "プロフィール", "外观": "外観", "语言": "言語", "采样": "サンプリング",
            "发送": "送信", "记忆": "記憶", "暂无长期记忆": "長期記憶はありません", "未设置身份": "プロフィール未設定", "当前：": "現在: "
        ],
        .korean: [
            "计划": "계획", "目标": "목표", "今日": "오늘", "规划": "플래닝", "监控": "모니터", "教练": "코치", "设置": "설정",
            "记录与教练": "기록 및 코치", "工作台": "워크스페이스", "待开始": "예정", "进行中": "진행 중", "已完成": "완료", "低": "낮음", "中": "보통", "高": "높음",
            "日间": "주간", "暗夜": "야간", "自定义": "사용자 지정", "今日计划": "오늘의 계획", "暂无今日计划": "오늘 계획 없음", "目标推进": "목표 진행", "暂无长期目标": "장기 목표 없음",
            "长期目标与短期计划": "장기 목표와 단기 계획", "新计划": "새 계획", "计划名称": "계획 이름", "完成信号或备注": "완료 신호 또는 메모", "项目": "프로젝트", "开始日期": "시작일", "完成日期": "완료일", "优先级": "우선순위", "添加计划": "계획 추가",
            "新目标": "새 목표", "目标名称": "목표 이름", "为什么做": "이유", "衡量方式": "측정 방식", "添加目标": "목표 추가", "计划日历": "계획 달력", "目标日志": "목표 로그",
            "记录时长、应用分布与窗口轨迹": "기록 시간, 앱 사용, 창 기록", "对话、记忆与规划动作": "대화, 기억, 계획 작업", "身份信息": "신원 정보", "外观": "외관", "语言": "언어", "采样": "샘플링",
            "发送": "보내기", "记忆": "기억", "暂无长期记忆": "장기 기억 없음", "未设置身份": "신원 미설정", "当前：": "현재: "
        ],
        .french: [
            "计划": "Plan", "目标": "Objectif", "今日": "Aujourd'hui", "规划": "Planification", "监控": "Suivi", "教练": "Coach", "设置": "Réglages",
            "记录与教练": "Journal et coach", "工作台": "Espace de travail", "待开始": "Prévu", "进行中": "En cours", "已完成": "Terminé", "低": "Basse", "中": "Moyenne", "高": "Haute",
            "日间": "Jour", "暗夜": "Nuit", "自定义": "Personnalisé", "今日计划": "Plans du jour", "暂无今日计划": "Aucun plan aujourd'hui", "目标推进": "Progression des objectifs", "暂无长期目标": "Aucun objectif long terme",
            "长期目标与短期计划": "Objectifs long terme et plans court terme", "新计划": "Nouveau plan", "计划名称": "Nom du plan", "完成信号或备注": "Signal de fin ou note", "项目": "Projet", "开始日期": "Date de début", "完成日期": "Date de fin", "优先级": "Priorité", "添加计划": "Ajouter le plan",
            "新目标": "Nouvel objectif", "目标名称": "Nom de l'objectif", "为什么做": "Pourquoi", "衡量方式": "Mesure", "添加目标": "Ajouter l'objectif", "计划日历": "Calendrier des plans", "目标日志": "Journaux d'objectifs",
            "记录时长、应用分布与窗口轨迹": "Temps enregistré, applications et fenêtres", "对话、记忆与规划动作": "Conversation, mémoire et actions", "身份信息": "Identité", "外观": "Apparence", "语言": "Langue", "采样": "Échantillonnage",
            "发送": "Envoyer", "记忆": "Mémoire", "暂无长期记忆": "Aucune mémoire longue", "未设置身份": "Identité non définie", "当前：": "Actuel : "
        ],
        .spanish: [
            "计划": "Plan", "目标": "Meta", "今日": "Hoy", "规划": "Planificación", "监控": "Monitor", "教练": "Coach", "设置": "Ajustes",
            "记录与教练": "Registro y coach", "工作台": "Espacio de trabajo", "待开始": "Planificado", "进行中": "En curso", "已完成": "Completado", "低": "Baja", "中": "Media", "高": "Alta",
            "日间": "Día", "暗夜": "Noche", "自定义": "Personalizado", "今日计划": "Planes de hoy", "暂无今日计划": "Sin planes para hoy", "目标推进": "Progreso de metas", "暂无长期目标": "Sin metas a largo plazo",
            "长期目标与短期计划": "Metas a largo plazo y planes a corto plazo", "新计划": "Nuevo plan", "计划名称": "Nombre del plan", "完成信号或备注": "Señal de finalización o nota", "项目": "Proyecto", "开始日期": "Fecha de inicio", "完成日期": "Fecha de finalización", "优先级": "Prioridad", "添加计划": "Añadir plan",
            "新目标": "Nueva meta", "目标名称": "Nombre de la meta", "为什么做": "Por qué", "衡量方式": "Medida", "添加目标": "Añadir meta", "计划日历": "Calendario de planes", "目标日志": "Registros de metas",
            "记录时长、应用分布与窗口轨迹": "Tiempo registrado, uso de apps y ventanas", "对话、记忆与规划动作": "Chat, memoria y acciones", "身份信息": "Identidad", "外观": "Apariencia", "语言": "Idioma", "采样": "Muestreo",
            "发送": "Enviar", "记忆": "Memoria", "暂无长期记忆": "Sin memoria a largo plazo", "未设置身份": "Identidad no definida", "当前：": "Actual: "
        ]
    ]
}

func L(_ key: String) -> String {
    TraceLocalization.text(key)
}
